[build]
  command = "echo 'No build step needed - static site with API functions'"
  functions = "netlify_functions"
  publish = "."

[functions]
  directory = "netlify_functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/reviews"
  to = "/.netlify/functions/reviews"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/reviews"
  status = 200

[[redirects]]
  from = "/api/billboard"
  to = "/.netlify/functions/billboard"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.12"
